### ISSUE TITLE
Documentation of Hacket

### ISSUE THREAD

**Issue by ShalokShalom** [takikawa/sweet-racket#42]
Hi there :)

I am currently a little bit confused about the Hacket [documentation](https://docs.racket-lang.org/hackett/). Since it is such a different language, is it a bit confusing to see at a first glance, how sweet applies here. 

Is there some rule of thumb?

**Comment by takikawa** [comment]
Hello. You can use this package with Hackett by applying the `sweet-exp` language mixin to Hackett's language. That would look like this declaration at the top of your Racket file:

`#lang sweet-exp hackett`

Sweet expressions work for most Racket language that uses s-expressions. Since Hackett uses s-expressions, using sweet expressions with it will work like any other sweet-exp use. For example:

```
#lang sweet-exp hackett
  
defn square
  [[x] *(x x)]

main $ println $ show $ square(3)
```

BTW: I would encourage asking this kind of question on the Racket mailing list or slack channel, you'll probably get help a lot sooner that way. Please use github issues to report bugs or feature requests. Cheers.
